iiko_transactions_data_frame = {
    "reportType": "TRANSACTIONS",
    "groupByRowFields": [
        "Session.GroupId",
        "OrderId",
        "Product.Category.Id",
        "Counteragent.Id",
        "Product.Tags.IdsCombo",
        "Product.Tag.Id",
        "Account.Id",
        "Product.Id",
        "Product.Num",
        "Product.AccountingCategory",
        "DateTime.Year",
        "Session.Group",
        "Contr-Product.AlcoholClass.Group",
        "Product.AlcoholClass.Group",
        "Contr-Account.Group",
        "Product.TopParent",
        "Product.SecondParent",
        "Product.ThirdParent",
        "Account.Group",
        "DateTime.Typed",
        "DateSecondary.DateTimeTyped",
        "DateSecondary.DateTyped",
        "TransactionSide",
        "DateTime.DayOfWeak",
        "Product.MeasureUnit",
        "Product.Hierarchy",
        "CashFlowCategory.Hierarchy",
        "Account.AccountHierarchyFull",
        "Session.CashRegister",
        "Department.Category1",
        "Department.Category2",
        "Department.Category3",
        "Department.Category4",
        "Department.Category5",
        "Product.Category",
        "DateTime.Quarter",
        "Contr-Product.AlcoholClass",
        "Product.AlcoholClass",
        "Contr-Product.AlcoholClass.Code",
        "Product.AlcoholClass.Code",
        "Conception.Code",
        "Contr-Account.Code",
        "Department.Code",
        "Account.Code",
        "TransactionType.Code",
        "Comment",
        "Counteragent.Name",
        "Conception",
        "Contr-Product.Category.Id",
        "Contr-Product.Tags.IdsCombo",
        "Contr-Product.Id",
        "Contr-Product.Num",
        "Contr-Product.AccountingCategory",
        "Contr-Product.TopParent",
        "Contr-Product.SecondParent",
        "Contr-Product.ThirdParent",
        "Contr-Product.MeasureUnit",
        "Contr-Product.Hierarchy",
        "Contr-Product.Category",
        "Contr-Product.Tags.NamesCombo",
        "Contr-Account.Name",
        "Contr-Product.CookingPlaceType",
        "Contr-Product.Type",
        "Contr-Product.Name",
        "DateTime.Month",
        "DateTime.WeekInYear",
        "DateTime.WeekInMonth",
        "Document",
        "OrderNum",
        "Session.RestaurantSection",
        "Product.Tags.NamesCombo",
        "Product.Tag.Name",
        "Store",
        "Account.StoreOrAccount",
        "CashFlowCategory",
        "CashFlowCategory.HierarchyLevel1",
        "CashFlowCategory.HierarchyLevel2",
        "CashFlowCategory.HierarchyLevel3",
        "Account.Name",
        "Account.AccountHierarchyTop",
        "Account.AccountHierarchySecond",
        "Account.AccountHierarchyThird",
        "Contr-Product.AlcoholClass.Type",
        "Product.AlcoholClass.Type",
        "Account.CounteragentType",
        "Contr-Account.Type",
        "Product.CookingPlaceType",
        "CashFlowCategory.Type",
        "Account.Type",
        "TransactionType",
        "Product.Type",
        "Department",
        "Account.IsCashFlowAccount",
        "DateTime.DateTyped",
        "DateTime.Hour",
        "Product.Name",
        "Department.JurPerson"
    ],
    "groupByColFields": [],
    "aggregateFields": [
        "Amount.Out",
        "Amount.In",
        "Sum.Outgoing",
        "Sum.Incoming",
        "Sum.ResignedSum"
    ],
    "filters": {
        "DateTime.Typed": {
            "filterType": "DateRange",
            "periodType": "CUSTOM",
            "from": "2025-09-29T00:00:00.000",
            "to": "2025-09-30T00:00:00.000"
        }
    }
}